Fixed Sensitive Data Exposure (File permission in attachments)
django-helpdesk/django-helpdesk pull request #1120
Opened 2023-10-06 11:43 UTC by fazledyn-or

This PR is made against https://github.com/django-helpdesk/django-helpdesk/issues/591#issuecomment-1744306396

# Problem Detail

The statement `os.umask(0)` in [models.py](https://github.com/django-helpdesk/django-helpdesk/blob/main/helpdesk/models.py#L1140) line 1140 and 1162 allows files and directories to be created with permission 777 - which is unsafe and leads to CWE-732. Not just that, **after the execution of this code, any files or directories are created with the same `mask`** and leads to permissions like `-rw-rw-rw-` or `drwxrwxrwx` .

Note: Even though the attachment directories are getting created with permission 777, the uploaded files are created with permission 644. Due to of Django's [FILE_UPLOAD_PERMISSIONS](https://docs.djangoproject.com/en/dev/ref/settings/#file-upload-permissions) setting.

## Proof of Concept

A proof-of-concept video has been created. You can find the video [here](https://drive.google.com/file/d/1PhCh8hHWiaweZHWE8_JNIE6zCAFTSEB-/view?usp=sharing) along with the [codebase](https://drive.google.com/file/d/1b1eU-YnIdDQnlTH5uB6JItpCLgIDPp3e/view?usp=sharing)

# Solution
Removing the statement(s) `os.umask(0)` and setting the mode to `755` for method `os.makedirs` in `attachment_path` eliminates the security flaw. A pull request for this fix has been created: 

***

### CLA Requirements:

This section is only relevant if your project requires contributors to sign a Contributor License Agreement (CLA) for external contributions. All contributed commits are already automatically signed off.

The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see [https://developercertificate.org/](https://developercertificate.org/) for more information).

- [Git Commit SignOff documentation](https://developercertificate.org/)

### Sponsorship and Support:

This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

2023-10-09 07:05 UTC, uhurusurfa requested changes
Would you mind putting the default value in settings.py so that it is configurable for those who might feel the need for even stricter permissions?

2023-10-09 07:41 UTC, fazledyn-or commented
Are you suggesting that I create a const, let's say `DIR_PERMISSION = 0o755` in `settings.py` and use it instead of the hard coded value? \- In that case, sure.

Otherwise, can you please elaborate?

2023-10-12 20:14 UTC, Benbb96 approved these changes

2023-10-13 06:24 UTC, uhurusurfa reviewed
Merging requires all unit tests to run and pass. Once #1104 which includes fixes for a few flaky unit tests is reviewed and merged we can get on with merging all the other PR's that are blocked by failing unit tests including this one..

2023-10-13 09:41 UTC, uhurusurfa approved these changes
👍  Thanks for the contribution

2023-10-13 09:41 UTC, merged