Add some convenient functions for protecting views in custom installations
django-helpdesk/django-helpdesk pull request #1161
Opened 2024-02-18 09:05 UTC by timthelion

Not sure if this needs to be merged into the main project but it sure would be convenient for me :) . Client needed to paywall the ticketing system and this was the easiest way ;)

2024-02-23 08:31 UTC, Benbb96 requested changes
I think it makes sense to add these possible checks in decorators. Could you just add the related documentation in order to show how they might be used, please?

The setting `VALID_EXTENSIONS` is documented but isn't present in `settings.py` so I believe it should be removed in profit for your `HELPDESK_VALIDATE_ATTACHMENT_TYPES`.

The tests also need to be adapted for this new setting I think.

2024-02-23 09:29 UTC, timthelion commented
Oops, I didn't realize that `VALID_EXTENSIONS` was documented. I'll update the docs, but not this week ;) No time...

2024-02-26 21:41 UTC, Benbb96 submitted a review, later dismissed
All good for me!

2024-03-01 22:58 UTC, timthelion commented
@uhurusurfa Can you merge this please?

2024-03-04 23:41 UTC, uhurusurfa requested changes
See inline comments

2024-03-04 23:41 UTC, uhurusurfa commented on docs/settings.rst
> -
Mark this as deprecated but continue to support it until some futiure release to maintain backwards compatibility.

2024-03-04 23:41 UTC, uhurusurfa commented on helpdesk/settings.py
> +
Use `VALID_EXTENSIONS` if it exists and fall back to `HELPDESK_VALID_EXTENSIONS` if empty to maintain backwards compatibility.

Failing there will ned to be clear upgrade notes telling users to change the name when they upgrade.

2024-04-22 16:29 UTC, timthelion commented on helpdesk/views/api.py
> +    `/api/tickets/?status=Open,Resolved` will return all the tickets that are Open or Resolved.
Somehow the idea of passing arbitrary numbers just felt less nice than having the names but you're right about the localization issue so I'll change it.

2024-04-29 20:26 UTC, uhurusurfa approved these changes

2024-04-29 20:26 UTC, merged